"""Headless check of the dashboard: every tab, the I did it price prompt, Skip, deep links and layout. Prints pass and fail counts."""
import sys, json
from playwright.sync_api import sync_playwright
URL = sys.argv[1]
results = []
def check(name, ok, info=""):
    results.append((name, bool(ok))); print(("PASS " if ok else "FAIL ") + name + (f"  ({info})" if info else ""))

with sync_playwright() as p:
    b = p.chromium.launch()
    for label, vw, vh in (("desktop", 1360, 950), ("phone", 390, 860)):
        ctx = b.new_context(viewport={"width": vw, "height": vh})
        pg = ctx.new_page()
        errs, sent = [], []
        pg.on("pageerror", lambda e: errs.append(str(e)))
        pg.on("console", lambda m: errs.append(m.text) if m.type == "error" and "fonts" not in m.text else None)
        pg.route("**/formResponse*", lambda r: (sent.append(r.request.url), r.fulfill(status=200, body="ok")))
        pg.goto(URL); pg.wait_for_selector("#hero h1")
        check(f"{label}: home loads with your money headline", "Your $100 is worth" in pg.inner_text("#hero h1"))
        check(f"{label}: dollars shown along the bottom of the money card", pg.locator("#hero .money b").count() == 4 and all("$" in t for t in pg.locator("#hero .money b").all_inner_texts()))
        check(f"{label}: no sideways scroll", pg.evaluate("document.documentElement.scrollWidth <= innerWidth + 1"))
        opens = pg.locator("#todo .slip").count()
        check(f"{label}: to-do lists the open signals", opens >= 1, opens)
        hrefs = pg.eval_on_selector_all("#todo [data-kraken]", "els=>els.map(e=>[e.textContent.trim(), e.getAttribute('href')])")
        check(f"{label}: each to-do has a Kraken button", len(hrefs) == opens, hrefs)
        ok_links = all(("pro.kraken.com/app/trade/" in h and "-usd" in h) or "kraken.com/stocks/" in h for _, h in hrefs)
        check(f"{label}: coins link to Kraken Pro trade, stocks to Kraken stocks", ok_links and any("sol-usd" in h for _, h in hrefs) and any("stocks/mstr" in h for _, h in hrefs))
        check(f"{label}: Kraken buttons say Buy or Sell", all(t.endswith("on Kraken") and t.split()[0] in ("Buy", "Sell") for t, _ in hrefs))
        first = pg.locator("#todo .slip").first
        sym = first.locator("h3").inner_text()
        first.locator("[data-log]").click()
        check(f"{label}: I did it opens the price prompt", pg.locator("#scrim.on").count() == 1)
        pre = pg.input_value("#sh-price")
        check(f"{label}: prompt starts with the signal price", pre not in ("", "0"), pre)
        pg.fill("#sh-price", "117.5")
        pg.click("#sh-save"); pg.wait_for_timeout(600)
        check(f"{label}: saving sends the trade to the Google form", len(sent) == 1, len(sent))
        u = sent[0] if sent else ""
        check(f"{label}: form gets Done, Kraken and the price you typed", "Done" in u and "Kraken" in u and "117.5" in u, u[-80:])
        check(f"{label}: prompt closes and the alert clears from the to-do", pg.locator("#scrim.on").count() == 0 and pg.locator("#todo .slip").count() == opens - 1)
        check(f"{label}: what you own now lists the buy", pg.locator("#own .row").count() >= 1 and "117.50" in pg.inner_text("#own"))
        if pg.locator("#todo [data-skip]").count():
            pg.locator("#todo [data-skip]").first.click(); pg.wait_for_timeout(500)
            check(f"{label}: Skip logs Skipped without a prompt", len(sent) == 2 and "Skipped" in sent[-1] and pg.locator("#scrim.on").count() == 0)
        check(f"{label}: to-do goes calm when nothing is left", "Nothing to do" in pg.inner_text("#todo"))
        for tab, sel in (("activity", "#activity .act"), ("lanes", "#lanesfull .lp"), ("settings", "#mytrades .lk"), ("home", "#own")):
            pg.click(f"#t-{tab}")
            check(f"{label}: {tab} tab shows its page", pg.locator(f"#p-{tab}").is_visible() and pg.locator(sel).count() > 0 and pg.evaluate("location.hash") == "#" + tab)
        pg.click("#t-activity")
        check(f"{label}: activity shows you did it with your price", "You did it" in pg.inner_text("#activity") and "117.50" in pg.inner_text("#activity"))
        pg.click("#t-settings")
        txt = pg.inner_text("#mytrades")
        check(f"{label}: my trades has the Sheet and form links", "My Sheet" in txt and "My trade form" in txt)
        check(f"{label}: settings shows how to get the app", "Get the app" in pg.inner_text("#rules"))
        pg.click("#t-home")
        heads = pg.locator("#heads .t").all_inner_texts()
        check(f"{label}: headlines are readable English", all(sum(ord(c) < 128 for c in h) / max(len(h), 1) > 0.95 for h in heads), len(heads))
        pg.reload(); pg.wait_for_selector("#hero h1")
        check(f"{label}: your logged trade survives a reload", "117.50" in pg.inner_text("#own"))
        check(f"{label}: no script errors", not errs, "; ".join(errs)[:160])
        pg.screenshot(path=f"/tmp/final_{label}.png", full_page=True)
        ctx.close()
    ctx = b.new_context(viewport={"width": 390, "height": 860}); pg = ctx.new_page()
    pg.goto(URL); pg.wait_for_selector("#hero h1")
    man = pg.evaluate("fetch('manifest.webmanifest').then(r=>r.json())")
    check("app manifest loads with name, start page and icons", man.get("display") == "standalone" and len(man.get("icons", [])) >= 3 and man.get("start_url"))
    icons_ok = pg.evaluate("Promise.all(['icons/icon-192.png','icons/icon-512.png','icons/maskable-512.png','icons/apple-touch-icon.png'].map(u=>fetch(u).then(r=>r.ok&&r.headers.get('content-type').includes('png')))).then(a=>a.every(Boolean))")
    check("all four app icons load", icons_ok)
    pg.wait_for_timeout(1500)
    sw = pg.evaluate("navigator.serviceWorker.getRegistration().then(r=>!!(r&&(r.active||r.installing||r.waiting)))")
    check("offline helper (service worker) registers", sw)
    ctx.set_offline(True); pg.reload(); pg.wait_for_timeout(1200)
    check("app still opens with no connection", pg.locator("#hero").count() == 1)
    ctx.set_offline(False)
    aid = pg.evaluate("signals().find(a=>statusOf(a)==='open').id")
    pg.goto(URL + "#log-" + aid); pg.reload(); pg.wait_for_timeout(1500)
    check("phone alert link opens straight into the price prompt", pg.locator("#scrim.on").count() == 1)
    pg.keyboard.press("Escape")
    check("Escape closes the prompt", pg.locator("#scrim.on").count() == 0)
    ctx.close()
    pg = b.new_page(); pg.goto(URL + "?data=/missing/"); pg.wait_for_timeout(2500)
    check("missing data shows a plain message", "Can't reach the race data" in pg.inner_text("#error"))
    b.close()
passed = sum(r[1] for r in results)
print(f"\n{passed} passed, {len(results) - passed} failed, {len(results)} checks")
sys.exit(0 if passed == len(results) else 1)
